# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/animList.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_animationList(object):
    def setupUi(self, animationList):
        animationList.setObjectName("animationList")
        animationList.setWindowModality(QtCore.Qt.WindowModal)
        animationList.resize(263, 380)
        self.verticalLayout = QtWidgets.QVBoxLayout(animationList)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.anim_lbl = QtWidgets.QLabel(animationList)
        self.anim_lbl.setObjectName("anim_lbl")
        self.verticalLayout.addWidget(self.anim_lbl)
        self.listView = QtWidgets.QListView(animationList)
        self.listView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.action_btn_layout = QtWidgets.QGridLayout()
        self.action_btn_layout.setSpacing(0)
        self.action_btn_layout.setObjectName("action_btn_layout")
        self.merge_btn = QtWidgets.QPushButton(animationList)
        self.merge_btn.setObjectName("merge_btn")
        self.action_btn_layout.addWidget(self.merge_btn, 0, 2, 1, 1)
        self.dup_btn = QtWidgets.QPushButton(animationList)
        self.dup_btn.setObjectName("dup_btn")
        self.action_btn_layout.addWidget(self.dup_btn, 0, 1, 1, 1)
        self.add_btn = QtWidgets.QPushButton(animationList)
        self.add_btn.setObjectName("add_btn")
        self.action_btn_layout.addWidget(self.add_btn, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.action_btn_layout)

        self.retranslateUi(animationList)
        QtCore.QMetaObject.connectSlotsByName(animationList)

    def retranslateUi(self, animationList):
        _translate = QtCore.QCoreApplication.translate
        animationList.setWindowTitle(_translate("animationList", "AnimationList"))
        self.anim_lbl.setText(_translate("animationList", "Animations"))
        self.merge_btn.setText(_translate("animationList", "Merge"))
        self.dup_btn.setText(_translate("animationList", "Duplicate"))
        self.add_btn.setText(_translate("animationList", "Add"))
