# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/spritesheets.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ani(object):
    def setupUi(self, ani):
        ani.setObjectName("ani")
        ani.resize(355, 346)
        self.verticalLayout = QtWidgets.QVBoxLayout(ani)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ani)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spritesheetView = QtWidgets.QListView(ani)
        self.spritesheetView.setObjectName("spritesheetView")
        self.verticalLayout.addWidget(self.spritesheetView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(ani)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(ani)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(ani)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(ani)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(ani)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(ani)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(ani)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ani)
        QtCore.QMetaObject.connectSlotsByName(ani)

    def retranslateUi(self, ani):
        _translate = QtCore.QCoreApplication.translate
        ani.setWindowTitle(_translate("ani", "Form"))
        self.label.setText(_translate("ani", "Spritesheets"))
        self.pushButton_4.setText(_translate("ani", "Add"))
        self.pushButton_3.setText(_translate("ani", "Reload"))
        self.pushButton_2.setText(_translate("ani", "Replace"))
        self.pushButton.setText(_translate("ani", "Remove Unused"))
        self.pushButton_5.setText(_translate("ani", "Select All"))
        self.pushButton_6.setText(_translate("ani", "Select None"))
        self.pushButton_7.setText(_translate("ani", "Save"))
