# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/spritesheet_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sprite_editor(object):
    def setupUi(self, sprite_editor):
        sprite_editor.setObjectName("sprite_editor")
        sprite_editor.resize(365, 358)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(sprite_editor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.functional_layout = QtWidgets.QHBoxLayout()
        self.functional_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.functional_layout.setSpacing(5)
        self.functional_layout.setObjectName("functional_layout")
        self.groupBox = QtWidgets.QGroupBox(sprite_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(50, 75))
        self.groupBox.setMaximumSize(QtCore.QSize(100, 75))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_x_lbl = QtWidgets.QLabel(self.groupBox)
        self.info_x_lbl.setObjectName("info_x_lbl")
        self.verticalLayout_2.addWidget(self.info_x_lbl)
        self.indo_y_lbl = QtWidgets.QLabel(self.groupBox)
        self.indo_y_lbl.setObjectName("indo_y_lbl")
        self.verticalLayout_2.addWidget(self.indo_y_lbl)
        self.functional_layout.addWidget(self.groupBox)
        self.bcg_group = QtWidgets.QGroupBox(sprite_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcg_group.sizePolicy().hasHeightForWidth())
        self.bcg_group.setSizePolicy(sizePolicy)
        self.bcg_group.setMinimumSize(QtCore.QSize(175, 75))
        self.bcg_group.setMaximumSize(QtCore.QSize(175, 75))
        self.bcg_group.setCheckable(False)
        self.bcg_group.setObjectName("bcg_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bcg_group)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tranparent_chkbox = QtWidgets.QCheckBox(self.bcg_group)
        self.tranparent_chkbox.setObjectName("tranparent_chkbox")
        self.verticalLayout.addWidget(self.tranparent_chkbox)
        self.show_border_chkbox = QtWidgets.QCheckBox(self.bcg_group)
        self.show_border_chkbox.setObjectName("show_border_chkbox")
        self.verticalLayout.addWidget(self.show_border_chkbox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.bcg_group)
        self.graphicsView_2.setMaximumSize(QtCore.QSize(30, 50))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout.addWidget(self.graphicsView_2)
        self.functional_layout.addWidget(self.bcg_group)
        self.pushButton = QtWidgets.QPushButton(sprite_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.functional_layout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.functional_layout)
        self.graphic_view = QtWidgets.QGraphicsView(sprite_editor)
        self.graphic_view.setMouseTracking(True)
        self.graphic_view.setStyleSheet("")
        self.graphic_view.setObjectName("graphic_view")
        self.verticalLayout_3.addWidget(self.graphic_view)

        self.retranslateUi(sprite_editor)
        QtCore.QMetaObject.connectSlotsByName(sprite_editor)

    def retranslateUi(self, sprite_editor):
        _translate = QtCore.QCoreApplication.translate
        sprite_editor.setWindowTitle(_translate("sprite_editor", "Form"))
        self.groupBox.setTitle(_translate("sprite_editor", "Info:"))
        self.info_x_lbl.setText(_translate("sprite_editor", "X:"))
        self.indo_y_lbl.setText(_translate("sprite_editor", "Y:"))
        self.bcg_group.setTitle(_translate("sprite_editor", "Background"))
        self.tranparent_chkbox.setText(_translate("sprite_editor", "Transparent"))
        self.show_border_chkbox.setText(_translate("sprite_editor", "Show Border"))
        self.pushButton.setText(_translate("sprite_editor", "Center View"))
